/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admin: AdminAuthOperations;
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    admin: Admin;
    users: User;
    media: Media;
    executives: Executive;
    'comp-teams': CompTeam;
    faqs: Faq;
    events: Event;
    'social-sessions': SocialSession;
    'social-session-registrations': SocialSessionRegistration;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admin: AdminSelect<false> | AdminSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    executives: ExecutivesSelect<false> | ExecutivesSelect<true>;
    'comp-teams': CompTeamsSelect<false> | CompTeamsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'social-sessions': SocialSessionsSelect<false> | SocialSessionsSelect<true>;
    'social-session-registrations': SocialSessionRegistrationsSelect<false> | SocialSessionRegistrationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin | User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Club executive accounts with full CMS access.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admin';
}
/**
 * Club member accounts used for social session registration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Member's first name.
   */
  firstName: string;
  /**
   * Member's last name.
   */
  lastName: string;
  /**
   * University of Auckland UPI, if the member is a UoA student.
   */
  upi?: string | null;
  /**
   * Contact phone number.
   */
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Uploaded images referenced by events, social sessions, and executives.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Alt text describing the image for screen readers and accessibility.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Club executive profiles shown on the public Executive Team page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executives".
 */
export interface Executive {
  id: string;
  /**
   * Full name of the executive.
   */
  name: string;
  /**
   * Role title, e.g. 'President', 'Treasurer', 'Social Coordinator'.
   */
  role: string;
  /**
   * Profile photo for the executive's card.
   */
  photo?: (string | null) | Media;
  /**
   * Degree of study, e.g 'BCom', 'BSc'.
   */
  degree?: string | null;
  /**
   * Main volleyball position, e.g 'Outside', 'Libero', 'Setter'.
   */
  position?: string | null;
  /**
   * Years of volleyball experience.
   */
  yearsOfExperience?: number | null;
  /**
   * Display order on the executive team page. Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Competitive squads and their rosters, shown on the public About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comp-teams".
 */
export interface CompTeam {
  id: string;
  /**
   * Squad name, e.g. 'UOAVC Mens'.
   */
  name: string;
  /**
   * Team photo shown above the roster.
   */
  photo?: (string | null) | Media;
  /**
   * Coach's name. Displayed under the roster as 'Coached by <name>'.
   */
  coach?: string | null;
  /**
   * Squad roster, listed in the order set here.
   */
  players?:
    | {
        /**
         * Player name as displayed, e.g. 'C. Kevin'.
         */
        name: string;
        /**
         * Playing position, e.g. 'Setter', 'Outside', 'Libero'.
         */
        position: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Display order on the About page. Lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently asked questions shown on the public FAQ page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: string;
  /**
   * Category of question, determines which category this FAQ displays under on the FAQ page
   */
  category: 'general' | 'sign-up';
  /**
   * The question, shown as the FAQ entry heading.
   */
  question: string;
  /**
   * The answer, supports rich formatting and links.
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Display order on the FAQ page. Lower numbers appear first.
   */
  order?: number | null;
  /**
   * If unchecked, this FAQ is hidden from the public and visible only to admins.
   */
  published: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * Display-only event cards. Sign-ups go to an external Google Form via googleFormUrl.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Public-facing title of the event.
   */
  title: string;
  /**
   * Full description shown on the event card.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date the event takes place.
   */
  date: string;
  /**
   * Start time, e.g. '7:00pm'.
   */
  startTime: string;
  /**
   * End time, e.g. '9:00pm'.
   */
  endTime?: string | null;
  /**
   * Venue or address for the event.
   */
  location: string;
  /**
   * Event price in NZD. Leave blank for a free event.
   */
  price?: number | null;
  /**
   * Optional cover image for the event card.
   */
  image?: (string | null) | Media;
  /**
   * External Google Form URL for sign-ups. Event card will link out to this URL.
   */
  googleFormUrl?: string | null;
  /**
   * Lifecycle state of the event.
   */
  status: 'upcoming' | 'completed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * Weekly club social sessions with registration, capacity limits, and pricing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-sessions".
 */
export interface SocialSession {
  id: string;
  /**
   * Public-facing title of the social session.
   */
  title: string;
  /**
   * Full description shown on the social session page.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Date the session takes place.
   */
  date: string;
  /**
   * Start time, e.g. '7:00pm'.
   */
  startTime: string;
  /**
   * End time, e.g. '9:00pm'.
   */
  endTime?: string | null;
  /**
   * Venue or address for the session.
   */
  location: string;
  /**
   * Optional cover image for the session card.
   */
  image?: (string | null) | Media;
  /**
   * Maximum number of confirmed registrations before new sign-ups go to the waitlist.
   */
  maxCapacity: number;
  /**
   * Maximum number of waitlisted registrations. Set to 0 to disable the waitlist.
   */
  waitlistCapacity: number;
  /**
   * Price charged to authenticated club members. Leave blank for free.
   */
  memberPrice?: number | null;
  /**
   * Price charged to guests (non-members). Leave blank for free.
   */
  nonMemberPrice?: number | null;
  /**
   * When registration opens. Registrations before this time are rejected.
   */
  registrationOpenAt?: string | null;
  /**
   * When registration closes. Registrations after this time are rejected.
   */
  registrationCloseAt?: string | null;
  /**
   * Lifecycle state of the session.
   */
  status: 'upcoming' | 'ongoing' | 'completed' | 'cancelled';
  updatedAt: string;
  createdAt: string;
}
/**
 * Member and guest registrations for social sessions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-session-registrations".
 */
export interface SocialSessionRegistration {
  id: string;
  /**
   * The social session being registered for.
   */
  socialSession: string | SocialSession;
  /**
   * Authenticated member, if any. Left blank for guest registrations.
   */
  user?: (string | null) | User;
  /**
   * Full name for guest (non-member) registrations.
   */
  guestName?: string | null;
  /**
   * Contact email for guest (non-member) registrations.
   */
  guestEmail?: string | null;
  /**
   * Current state of this registration.
   */
  registrationStatus: 'registered' | 'waitlisted' | 'cancelled';
  /**
   * Timestamp the registration was created.
   */
  registeredAt: string;
  /**
   * Amount paid (NZD). Null for free or pending registrations.
   */
  amountPaid?: number | null;
  /**
   * Payment state for paid social sessions.
   */
  paymentStatus?: ('pending' | 'paid' | 'free' | 'refunded') | null;
  /**
   * Stripe Checkout Session ID used to reconcile webhook events to this registration.
   */
  stripeCheckoutSessionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'admin';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'executives';
        value: string | Executive;
      } | null)
    | ({
        relationTo: 'comp-teams';
        value: string | CompTeam;
      } | null)
    | ({
        relationTo: 'faqs';
        value: string | Faq;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'social-sessions';
        value: string | SocialSession;
      } | null)
    | ({
        relationTo: 'social-session-registrations';
        value: string | SocialSessionRegistration;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'admin';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'admin';
        value: string | Admin;
      }
    | {
        relationTo: 'users';
        value: string | User;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  upi?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "executives_select".
 */
export interface ExecutivesSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  degree?: T;
  position?: T;
  yearsOfExperience?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comp-teams_select".
 */
export interface CompTeamsSelect<T extends boolean = true> {
  name?: T;
  photo?: T;
  coach?: T;
  players?:
    | T
    | {
        name?: T;
        position?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  category?: T;
  question?: T;
  answer?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  price?: T;
  image?: T;
  googleFormUrl?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-sessions_select".
 */
export interface SocialSessionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  location?: T;
  image?: T;
  maxCapacity?: T;
  waitlistCapacity?: T;
  memberPrice?: T;
  nonMemberPrice?: T;
  registrationOpenAt?: T;
  registrationCloseAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-session-registrations_select".
 */
export interface SocialSessionRegistrationsSelect<T extends boolean = true> {
  socialSession?: T;
  user?: T;
  guestName?: T;
  guestEmail?: T;
  registrationStatus?: T;
  registeredAt?: T;
  amountPaid?: T;
  paymentStatus?: T;
  stripeCheckoutSessionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}